import type { Metadata } from "next";
import { Cairo, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers/providers";
import { responseUserType, useGetUser } from "@/hooks/useGetUser";
import { userType } from "@/types/types";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user: responseUserType | null = await useGetUser();

  return (
    <html lang="ar" dir="rtl">
      <body className={`antialiased ${cairo.variable}`}>
        <Providers user={user}>{children}</Providers>
      </body>
    </html>
  );
}
